# Generated by Django 2.1.4 on 2019-01-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costControl', '0002_auto_20190104_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operation',
            field=models.CharField(choices=[('Expenses', ''), ('Profits', '')], max_length=9),
        ),
    ]
